GK : Simon Mignolet
RB : Nathaniel Clyne
CB : Joel Matip
CB : Dejan Lovren
LB : James Milner
CM : Jordan Henderson
CM : Phillipe Coutinho
CM : Adam Lallana
RW : Sadio Mane
LW : Mo Salah
CF : Roberto Firmino